### ISSUE TITLE
How to disable ConfigurationWatcher?

### ISSUE THREAD

**Issue by orastarter** [mdavid/SuperSocket#2]
I am trying to change my config file and make mistake in connectionstring section not in supersocket. ConfigurationWatcher tries to read config and failed and my socket server stopped :(
How to disable ConfigurationWatcher?
Thank you

**Comment by orastarter** [comment]
https://github.com/kerryjiang/SuperSocket/issues/131

**Comment by kerryjiang** [comment]
Yes, it doesn't have this option for now.
